### ISSUE TITLE
"Unknown error occurred" on adding new battery

### ISSUE THREAD

**Issue by HindrikDeelstra** [hif2k1/battery_sim#105]
Using Home Assistant Core 2023.11.3 I was previously able to add batteries via the battery_sim integration, but no longer.

I've tried all different versions, currently using the latest version (1.3.1)

Adding the integration, and choosing a random battery (Sessy for instance), throws an "Unknown error occurred" in the "Select battery" pop-up.

With debug-logging enabled, this is what I see upon choosing "Submit":

```
2023-12-06 16:04:52.543 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_handle_step
    self._raise_if_step_does_not_exist(flow, result["step_id"])
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 440, in _raise_if_step_does_not_exist
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ConfigEntriesFlowManager doesn't support step meterMenu

```

Can you help determine what's wrong, and how to fix this?

**Comment by HindrikDeelstra** [comment]
Thanks for your quick update!

Unfortunately, the issue remains for me. Seeing as you cannot reproduce it, it might just be some quirk or fault in my local HomeAssistant installation. The relevant part seems to be the last line:

`homeassistant.data_entry_flow.UnknownStep: Handler ConfigEntriesFlowManager doesn't support step meterMenu`

Somehow, it looks like HA is just not accepting the step_id="meterMenu" from the config_flow.py, but I would not know how to investigate that any further. I'm using HA in docker, so I could try to re-create the container and see if that helps.

In any case, I've managed to create the desired simulated battery via the configuration.yaml so it's usable for now ;) Should no updates follow, and I forget to, you may close this issue at your discretion...

**Comment by hif2k1** [comment]
Ok having updated my home assistant from October23 to November23 I have reproduced the error. I don't think the fix I tried works, but I will work on it over the next few days.

**Comment by HindrikDeelstra** [comment]
FYI: I've just updated my HA Core container to 2023.12.0 (so, the december update), and it's still producing the same error (but now with the updated step_id in version 1.3.2):

`homeassistant.data_entry_flow.UnknownStep: Handler ConfigEntriesFlowManager doesn't support step meter_menu`

Did HA perhaps change something in their ConfigEntriesFlowManager code for setting up integration configs in custom_components via the UI?

**Comment by hif2k1** [comment]
I think this is fixed now.

**Comment by r13ssh** [comment]
Hi @hif2ki,

Very happy New Year :-)

I just migrated from a dockerized HA installation to Hass-OS (virtualized via Proxmox) and I'm now getting this very same error, my battery_sim is v1.3.3, Homeassistant reports:

Core 2023.12.4 - Supervisor 2023.12.0 - Operating System 11.2 - Frontend 20231208.2

```
2024-01-01 01:32:23.337 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/battery_sim/config_flow.py", line 81, in async_step_custom
return await self.async_step_meter_menu()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/battery_sim/config_flow.py", line 106, in async_step_meter_menu
for input in self._data[CONF_INPUT_LIST]:
~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'input_list'
```

**Comment by hif2k1** [comment]
Ok, thanks for flagging this up. This is actually a different error and I haven't been able to reproduce it using the latest version of HA. It is an odd error as it seems not to be able to find a variable that is created in the same process. Just for clarity you were trying to set up a new battery using the config flow? Is that right? Did you add any meters or did the error happen straight away after selecting the batter type? Thanks.
