### ISSUE TITLE
 "Unknown error occurred" on adding new battery (re-ocurrance of #105)

### ISSUE THREAD

**Issue by r13ssh** [hif2k1/battery_sim#110]
After upgrading from homeassistant (dockerized) to HASS-OS 11.3 I'm running into the same issue described in #105 when trying to add a new custom battery.

Is there any workaround I could use?

```2024-01-08 22:42:06.450 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/battery_sim/config_flow.py", line 81, in async_step_custom
return await self.async_step_meter_menu()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/battery_sim/config_flow.py", line 106, in async_step_meter_menu
for input in self._data[CONF_INPUT_LIST]:
~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'input_list'```

**Comment by hif2k1** [comment]
In terms of a workaround: you can create a battery in the main home
assistant config or by editing the core.config_entries file in the .storage
folder.

I will try and make a fix, but it's odd that you are having this error.
COnfig_flow should execute the same regardless of your setup. I will try
and find a fix, but it's difficult as I can't create the same setup as you.

Hamish

**Comment by FritsOV** [comment]
Have the same problem. 
tried to configure a custom powerwall and got the error "unknown error"
If i fill in as custom device the default values available from the tesla powerwall e.g. 13,5  3,68, 5, 0.9  also an unknown error occurs.

**Comment by r13ssh** [comment]
yeah, the issue is not limited to custom batteries, same thing here. 

I did play around with the manual changing of `core.config_entries` but abandoned this when I bricked by test-instance :-)

**Comment by hif2k1** [comment]
Ok, I managed to reproduce the bug when setting up a custom battery and have posted a fix for this in the latest release. I haven't been able to get it to happen at other times, but the config_flow is now complex with lots of possible paths so if it is happening at another time please let me know what config steps you go through to trigger it and what error you get in the logs. Many thanks

**Comment by hif2k1** [comment]
Ok, I've re-opened it and will try to have a look through the log when I get time. Thanks

**Comment by r13ssh** [comment]
@hif2k1 - Thanks so much for this fix, I was just able to add my 2 simulated batteries back into my new installation!
