### ISSUE TITLE
Not working entities get status not available

### ISSUE THREAD

**Issue by JohanKrab** [hif2k1/battery_sim#122]
Log:

Logger: homeassistant.helpers.event
Source: helpers/event.py:296
First occurred: 13:57:03 (665 occurrences)
Last logged: 15:51:54

    Error while dispatching event for sensor.dsmr_reading_electricity_currently_returned to <Job track state_changed event ['sensor.dsmr_reading_electricity_currently_returned'] HassJobType.Callback <bound method SimulatedBatteryHandle.async_reading_handler of <custom_components.battery_sim.SimulatedBatteryHandle object at 0x7fcace901610>>>
    Error while dispatching event for sensor.dsmr_reading_electricity_currently_delivered to <Job track state_changed event ['sensor.dsmr_reading_electricity_currently_delivered'] HassJobType.Callback <bound method SimulatedBatteryHandle.async_reading_handler of <custom_components.battery_sim.SimulatedBatteryHandle object at 0x7fcace901610>>>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/battery_sim/__init__.py", line 337, in async_reading_handler
    new_state_value = float(new_state.state) * conversion_factor
                                               ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'conversion_factor' where it is not associated with a value

**Comment by brugk000** [comment]
I made the same mistake. You have to use sensors that represent kWh not kW.
I used the merged daily in and out sensors from DSMR:
sensor.dsmr_day_consumption_electricity_merged and
sensor.dsmr_day_consumption_electricity_returned_merged

**Comment by masminl** [comment]
> I made the same mistake. You have to use sensors that represent kWh not kW. I used the merged daily in and out sensors from DSMR: sensor.dsmr_day_consumption_electricity_merged and sensor.dsmr_day_consumption_electricity_returned_merged

I have the same issue. How did you merge the consumption and production sensor data?

**Comment by brugk000** [comment]
> > I made the same mistake. You have to use sensors that represent kWh not kW. I used the merged daily in and out sensors from DSMR: sensor.dsmr_day_consumption_electricity_merged and sensor.dsmr_day_consumption_electricity_returned_merged
> 
> I have the same issue. How did you merge the consumption and production sensor data?

You can add the json in DSMR MQTT topics:

![image](https://github.com/user-attachments/assets/bae943db-955b-4088-a533-30645e34d60f)

**Comment by masminl** [comment]
Thanks for sharing, but I'm afraid I'll have to solve this in another way...  
I use the 'DSMR Smart Meter' integration which simply connects to the P1 port. It works perfectly fine, but unfortunately doesn't expose any MQTT data.
Setting up DSMR Reader in Docker or as Add-on for HA seems to be overkill since it would only be needed to calculate the daily consumption/production of energy.
